version: "3.9"

services:
  flask-db:
    container_name: flask_db
    image: postgres:14.11
    ports:
      - "5433:5432"
    env_file:
      - .env.db.local
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-app:
    container_name: flask_api
    image: anzoid/hospital_api:1.0.0
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - flask-db

volumes:
  pgdata: {}

